spring.application.name=backend

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/gisdb
spring.datasource.username=gisuser
spring.datasource.password=gispass

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.toyproject.backend.domain
mybatis.configuration.map-underscore-to-camel-case=true
